#!/usr/bin/env bash
# write a Bash script that will display information about the subdomains.
# Display record types of subdomains.
# Usage:    ./0-world_wide_web <domain> <subdomain>.

# Function to get and show domain info.

show_domain_info () {
    # echo "$2 $(dig "$2"."$1" +noall +answer)" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ $# -eq 2 ]
then
    show_domain_info "$1" "$2"
elif [ $# -eq 1 ]
then
    show_domain_info "$1" www
    show_domain_info "$1" lb-01
    show_domain_info "$1" web-01
    show_domain_info "$1" web-02
fi
