#!/usr/bin/env bash
# This transfers a file from a client to a server
if [ $# -lt 4 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
fi

FILE_PATH="$1"
IP="$2"
USER="$3"
SSH_KEY="$4"
OPTION="-o StrictHostKeyChecking=no"
scp "$OPTION" -i "$SSH_KEY" "$FILE_PATH" "$USER"@"$IP":~/
