#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install nginx -y

# Add `index.html` file that contains 'Hello World!
echo "Hello World!" > index.html

# Move the file to where Nginx serves its web pages
sudo mv index.html /var/www/html/

# Restart Nginx
sudo service nginx restart
