#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install nginx -y

# Add `index.html` file that contains 'Hello World!
echo "Hello World!" > index.html

# Check if the redirection rule is already present
if ! grep -q "location /redirect_me {" /etc/nginx/sites-available/default; then
	# Redirect the link to youtube
	REDIRECT_RULE="\n\tlocation /redirect_me {\n\
			return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
		}"
	sudo sed -i "/server_name _;/a \ $REDIRECT_RULE" /etc/nginx/sites-available/default
	
	# Restart Nginx
	sudo service nginx restart
else
	 echo "Redirection rule already present. No changes made."
fi
