#!/usr/bin/env bash
# Configure `Nginx` web server so that each server contains its hostname in its response header
sudo apt-get update
sudo apt-get install nginx -y

# Add `index.html` file that contains 'Hello World!
echo "Hello World!" > index.html

# Move the file to where Nginx serves its web pages
sudo mv index.html /var/www/html/

# Redirect the link to youtube
REDIRECT_RULE="\n\tlocation /redirect_me {\n\
		           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
		       }"
sudo sed -i "/server_name _;/a \ $REDIRECT_RULE" /etc/nginx/sites-available/default

# Configure custom error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i "/server_name _;/a \ \n\terror_page 404 /404.html;" /etc/nginx/sites-available/default
sudo sed -i '/try_files.*=404/s/^/#/' /etc/nginx/sites-available/default
E404_RULE="\tlocation /404.html {\n\
        \troot /var/www/html;\n\
	\tinternal;\n\
	}"
sudo sed -i "/error_page.*404.*;/a \ $E404_RULE" /etc/nginx/sites-available/default

# Configure a custom header
sudo sed -i "/server_name _;/a \ \n\tadd_header X-Served-By \"$(hostname)\";" /etc/nginx/sites-available/default

sudo service nginx restart
