#!/usr/bin/env bash
# Install and configure a `HAProxy` load balancer
sudo apt-get update
sudo apt-get install haproxy -y

# Configuration
CONFIG="
backend http_back
	balance roundrobin
	server 337533-web-01 54.160.96.3:80 check
	server 337533-web-02 100.26.160.56:80 check

frontend http_front
	 bind *:80
	 default_backend http_back
"
echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
